import type { Metadata } from "next";
import "./globals.css";
import { fonts, montserrat } from "@/assets/fonts";
import DashboardNavbar from "@/components/layout/dashboard-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} flex min-h-screen flex-auto flex-shrink-0 flex-col text-black bg-background antialiased`}
      >
        <DashboardNavbar />
        <div className="ml-56">
          <div className=" p-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
