import { fonts, montserrat } from "@/assets/fonts";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="p-6">{children}</main>;
}
